package com.mycompany.view;

import javax.swing.JMenuItem;
import javax.swing.JTable;

public class MainCalculadorEstatistica extends javax.swing.JFrame {

    /**
     * Creates new form MainScreenView
     */
    public MainCalculadorEstatistica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblDados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniImportarDados = new javax.swing.JMenuItem();
        mniCalacular = new javax.swing.JMenuItem();
        mniVisualizarDados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestão de Pessoas");
        setBackground(new java.awt.Color(102, 102, 102));

        TblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblDados);

        jMenu1.setText("Opções");

        mniImportarDados.setText("Importar dados");
        mniImportarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniImportarDadosActionPerformed(evt);
            }
        });
        jMenu1.add(mniImportarDados);

        mniCalacular.setText("Calcular Dados");
        jMenu1.add(mniCalacular);

        mniVisualizarDados.setText("Visualizar Dados");
        mniVisualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarDadosActionPerformed(evt);
            }
        });
        jMenu1.add(mniVisualizarDados);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniVisualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniVisualizarDadosActionPerformed

    private void mniImportarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniImportarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniImportarDadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblDados;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mniCalacular;
    private javax.swing.JMenuItem mniImportarDados;
    private javax.swing.JMenuItem mniVisualizarDados;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMniCalacular() {
        return mniCalacular;
    }

    public void setMniCalacular(JMenuItem mniCalacular) {
        this.mniCalacular = mniCalacular;
    }

    public JMenuItem getMniImportarDados() {
        return mniImportarDados;
    }

    public void setMniImportarDados(JMenuItem mniImportarDados) {
        this.mniImportarDados = mniImportarDados;
    }

    public JMenuItem getMniVisualizarDados() {
        return mniVisualizarDados;
    }

    public void setMniVisualizarDados(JMenuItem mniVisualizarDados) {
        this.mniVisualizarDados = mniVisualizarDados;
    }

    public JTable getTblDados() {
        return TblDados;
    }

    public void setTblDados(JTable TblDados) {
        this.TblDados = TblDados;
    }

}
